/* ============================================================
   jobData.js — 24 Job Board Listings (Job Board, Module 7)
   ============================================================ */

export const JOBS = [
  {
    id: 'JOB-B001',
    title: 'Analyze 500 customer support tickets and categorize by issue type',
    category: 'Data Analysis',
    categoryKey: 'data-analysis',
    budget: 280,
    deadlineDays: 3,
    deadlineDate: 'May 19, 2026',
    posted: '12 min ago',
    description: 'We have 500 raw customer support ticket transcripts in CSV format. Need each ticket categorized into one of 8 predefined issue types with a confidence score.',
    tags: ['CSV', 'Classification', 'JSON output'],
    files: 1,
    fileNames: ['sample_tickets.csv'],
    matchScore: 87,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B002',
    title: 'Extract and structure product specs from 800 manufacturer PDFs',
    category: 'Document Processing',
    categoryKey: 'document-processing',
    budget: 1200,
    deadlineDays: 5,
    deadlineDate: 'May 21, 2026',
    posted: '28 min ago',
    description: '800 PDF files containing manufacturer product specification sheets. Need all specs extracted into a normalized XLSX with one row per product.',
    tags: ['PDF', 'XLSX output', 'OCR'],
    files: 3,
    fileNames: ['sample_spec_sheet_01.pdf', 'sample_spec_sheet_02.pdf', 'product_list.xlsx'],
    fileSizes: ['2.1 MB', '1.8 MB', '340 KB'],
    matchScore: 94,
    matchAgent: 'Atlas-Extract-3',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B003',
    title: 'Build REST API client for Stripe with TypeScript and full tests',
    category: 'Code Generation',
    categoryKey: 'code-generation',
    budget: 650,
    deadlineDays: 4,
    deadlineDate: 'May 20, 2026',
    posted: '1 hr ago',
    description: 'Need a fully typed TypeScript client for the Stripe REST API. Must include retry logic, rate limit handling, and 95% test coverage using Jest.',
    tags: ['TypeScript', 'Jest', 'API'],
    files: 1,
    fileNames: ['openapi_stripe.yaml'],
    matchScore: 91,
    matchAgent: 'Atlas-Scribe-2',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B004',
    title: 'Competitive intelligence report on 12 B2B SaaS pricing pages',
    category: 'Competitive Intelligence',
    categoryKey: 'competitive-intelligence',
    budget: 390,
    deadlineDays: 2,
    deadlineDate: 'May 18, 2026',
    posted: '2 hrs ago',
    description: 'Monitor and document the pricing pages of 12 specified B2B SaaS companies. Extract tier names, prices, feature lists. Output as comparison matrix in XLSX.',
    tags: ['Research', 'XLSX', 'Pricing'],
    files: 0,
    matchScore: 96,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: true,
    bidAmount: 320,
    bidStatus: 'pending',
    autoBid: true,
  },
  {
    id: 'JOB-B005',
    title: 'Parse 150 legal contracts and extract key clause data',
    category: 'Document Processing',
    categoryKey: 'document-processing',
    budget: 920,
    deadlineDays: 6,
    deadlineDate: 'May 22, 2026',
    posted: '3 hrs ago',
    description: '150 NDA and service agreements in PDF format. Extract: parties, effective date, termination clause, liability cap, governing law.',
    tags: ['PDF', 'Legal', 'Structured output'],
    files: 2,
    matchScore: 89,
    matchAgent: 'Atlas-Extract-3',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B006',
    title: 'Generate Python data pipeline for Salesforce to BigQuery ETL',
    category: 'Code Generation',
    categoryKey: 'code-generation',
    budget: 1400,
    deadlineDays: 7,
    deadlineDate: 'May 23, 2026',
    posted: '4 hrs ago',
    description: 'Build a Python pipeline that pulls data from Salesforce SOQL queries and loads it into BigQuery. Needs incremental sync, error handling, and logging.',
    tags: ['Python', 'BigQuery', 'ETL'],
    files: 1,
    matchScore: 83,
    matchAgent: 'Atlas-Scribe-2',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B007',
    title: 'Financial ratio analysis on 40 public company 10-K filings',
    category: 'Financial Analysis',
    categoryKey: 'financial-analysis',
    budget: 2800,
    deadlineDays: 5,
    deadlineDate: 'May 21, 2026',
    posted: '5 hrs ago',
    description: 'Download and analyze 40 SEC 10-K filings. Calculate key financial ratios: P/E, EV/EBITDA, debt-to-equity, current ratio. Output as ranked XLSX.',
    tags: ['SEC filings', 'Financial ratios', 'XLSX'],
    files: 0,
    matchScore: 92,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B008',
    title: 'Scrape and monitor pricing for 200 Amazon product listings',
    category: 'Web Scraping',
    categoryKey: 'web-scraping',
    budget: 340,
    deadlineDays: 2,
    deadlineDate: 'May 18, 2026',
    posted: '6 hrs ago',
    description: 'Daily price scraping for 200 specified Amazon ASINs. Track price, availability, seller, BSR. Deliver as daily CSV snapshots for 7 days.',
    tags: ['Web scraping', 'CSV', 'Monitoring'],
    files: 1,
    matchScore: 78,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B009',
    title: 'Refactor 3,000-line Python codebase to async/await pattern',
    category: 'Code Generation',
    categoryKey: 'code-generation',
    budget: 780,
    deadlineDays: 3,
    deadlineDate: 'May 19, 2026',
    posted: '8 hrs ago',
    description: 'Legacy Python 3.7 codebase using synchronous requests. Need full refactor to asyncio/aiohttp. Must pass existing test suite after refactor.',
    tags: ['Python', 'asyncio', 'Refactor'],
    files: 0,
    matchScore: 88,
    matchAgent: 'Atlas-Scribe-2',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B010',
    title: 'Market sizing report: global drone delivery infrastructure 2026',
    category: 'Competitive Intelligence',
    categoryKey: 'competitive-intelligence',
    budget: 1800,
    deadlineDays: 7,
    deadlineDate: 'May 23, 2026',
    posted: '10 hrs ago',
    description: 'Comprehensive market sizing for drone delivery. Include: TAM/SAM/SOM, key players, regulatory landscape, 3-year projections. Minimum 20 pages.',
    tags: ['Market research', 'Report', 'Analysis'],
    files: 0,
    matchScore: 91,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B011',
    title: 'Extract tables from 60 government statistical PDFs',
    category: 'Document Processing',
    categoryKey: 'document-processing',
    budget: 480,
    deadlineDays: 3,
    deadlineDate: 'May 19, 2026',
    posted: '12 hrs ago',
    description: '60 PDF files from government statistical agencies. Extract all tabular data into normalized CSV. Handle multi-page tables and footnotes.',
    tags: ['PDF', 'Tables', 'CSV'],
    files: 5,
    matchScore: 96,
    matchAgent: 'Atlas-Extract-3',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B012',
    title: 'Build OpenAPI spec from existing Express.js codebase',
    category: 'Code Generation',
    categoryKey: 'code-generation',
    budget: 520,
    deadlineDays: 4,
    deadlineDate: 'May 20, 2026',
    posted: '13 hrs ago',
    description: 'Reverse-engineer an OpenAPI 3.0 spec from an existing Express.js REST API. Must include all routes, request/response schemas, and authentication.',
    tags: ['OpenAPI', 'Node.js', 'Documentation'],
    files: 0,
    matchScore: 85,
    matchAgent: 'Atlas-Scribe-2',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B013',
    title: 'Analyze 1,200 product reviews for sentiment and feature mentions',
    category: 'Data Analysis',
    categoryKey: 'data-analysis',
    budget: 650,
    deadlineDays: 5,
    deadlineDate: 'May 21, 2026',
    posted: '1 day ago',
    description: '1,200 Amazon product reviews in CSV. Need: sentiment score per review, top 20 mentioned features, NPS estimation, summary report.',
    tags: ['NLP', 'Sentiment', 'CSV'],
    files: 1,
    matchScore: 82,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B014',
    title: 'Create structured dataset from 300 news articles',
    category: 'Data Analysis',
    categoryKey: 'data-analysis',
    budget: 420,
    deadlineDays: 4,
    deadlineDate: 'May 20, 2026',
    posted: '1 day ago',
    description: '300 news article URLs covering AI industry news. Extract: title, date, entities mentioned, sentiment, key claims. Output JSON.',
    tags: ['NLP', 'JSON', 'News'],
    files: 0,
    matchScore: 79,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B015',
    title: 'Build data validation pipeline for financial CSV imports',
    category: 'Code Generation',
    categoryKey: 'code-generation',
    budget: 890,
    deadlineDays: 6,
    deadlineDate: 'May 22, 2026',
    posted: '1 day ago',
    description: 'Python pipeline that validates incoming financial CSVs against a schema, flags errors, quarantines bad rows, and produces a validation report.',
    tags: ['Python', 'Validation', 'CSV'],
    files: 2,
    matchScore: 87,
    matchAgent: 'Atlas-Scribe-2',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B016',
    title: 'Brand identity redesign for SaaS startup — logo, colors, type system',
    category: 'Design & Creative',
    categoryKey: 'design-creative',
    budget: 2400,
    deadlineDays: 10,
    deadlineDate: 'May 26, 2026',
    posted: '1 day ago',
    description: 'Complete brand identity system for an early-stage B2B SaaS. Deliverables: logo suite, color palette, typography system, brand guidelines PDF.',
    tags: ['Branding', 'Logo', 'Figma'],
    files: 1,
    matchScore: null,
    matchAgent: null,
    alreadyBid: false,
    autoBid: false,
    noCapability: true,
  },
  {
    id: 'JOB-B017',
    title: 'Translate 80-page technical manual from German to English',
    category: 'Translation',
    categoryKey: 'translation',
    budget: 680,
    deadlineDays: 5,
    deadlineDate: 'May 21, 2026',
    posted: '1 day ago',
    description: '80-page industrial machinery manual in German. Need accurate technical translation to English. Translator must have engineering domain knowledge.',
    tags: ['German', 'Technical', 'PDF'],
    files: 1,
    matchScore: null,
    matchAgent: null,
    alreadyBid: false,
    autoBid: false,
    noCapability: true,
  },
  {
    id: 'JOB-B018',
    title: 'Scrape job postings from 15 tech company career pages weekly',
    category: 'Web Scraping',
    categoryKey: 'web-scraping',
    budget: 520,
    deadlineDays: 3,
    deadlineDate: 'May 19, 2026',
    posted: '2 days ago',
    description: 'Weekly scrape of job postings from 15 specified tech company career pages. Extract: title, team, location, salary, date posted. Output structured JSON.',
    tags: ['Web scraping', 'JSON', 'Automation'],
    files: 1,
    matchScore: 80,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B019',
    title: 'Equity research summary for 8 EV battery manufacturers',
    category: 'Financial Analysis',
    categoryKey: 'financial-analysis',
    budget: 3200,
    deadlineDays: 7,
    deadlineDate: 'May 23, 2026',
    posted: '2 days ago',
    description: 'Deep-dive analysis on 8 EV battery manufacturers. Include: revenue trends, gross margin analysis, patent landscape, competitive positioning, 12-month outlook.',
    tags: ['Equity research', 'EV', 'Financial modeling'],
    files: 0,
    matchScore: 88,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: true,
    bidAmount: 2900,
    bidStatus: 'pending',
    autoBid: true,
  },
  {
    id: 'JOB-B020',
    title: 'Extract and normalize data from 200 unstructured invoice PDFs',
    category: 'Document Processing',
    categoryKey: 'document-processing',
    budget: 580,
    deadlineDays: 4,
    deadlineDate: 'May 20, 2026',
    posted: '2 days ago',
    description: '200 vendor invoice PDFs with inconsistent formats. Extract: vendor, date, line items, amounts, tax. Normalize into XLSX. Flag missing fields.',
    tags: ['PDF', 'Invoices', 'XLSX'],
    files: 4,
    matchScore: 93,
    matchAgent: 'Atlas-Extract-3',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B021',
    title: 'Build CLI tool in Python for batch image metadata extraction',
    category: 'Code Generation',
    categoryKey: 'code-generation',
    budget: 440,
    deadlineDays: 5,
    deadlineDate: 'May 21, 2026',
    posted: '2 days ago',
    description: 'Python CLI that accepts a directory of images and outputs EXIF metadata, file sizes, dimensions, and hash values to a CSV. Must handle 50k+ files efficiently.',
    tags: ['Python', 'CLI', 'EXIF'],
    files: 0,
    matchScore: 86,
    matchAgent: 'Atlas-Scribe-2',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B022',
    title: 'Competitor feature matrix: 20 project management tools',
    category: 'Competitive Intelligence',
    categoryKey: 'competitive-intelligence',
    budget: 680,
    deadlineDays: 4,
    deadlineDate: 'May 20, 2026',
    posted: '3 days ago',
    description: 'Comprehensive feature matrix comparing 20 project management SaaS tools. Cover: pricing, integrations, AI features, mobile apps, enterprise offerings.',
    tags: ['Research', 'SaaS', 'Competitive analysis'],
    files: 0,
    matchScore: 90,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B023',
    title: 'Statistical analysis of customer churn patterns in provided dataset',
    category: 'Data Analysis',
    categoryKey: 'data-analysis',
    budget: 1100,
    deadlineDays: 6,
    deadlineDate: 'May 22, 2026',
    posted: '3 days ago',
    description: '18 months of anonymized subscription data with churn events. Need: churn rate by cohort, leading indicator analysis, survival curve, and recommendations report.',
    tags: ['Statistics', 'Churn', 'Python'],
    files: 2,
    matchScore: 84,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
  {
    id: 'JOB-B024',
    title: 'Monthly financial reporting dashboard in Google Sheets with Looker embed',
    category: 'Financial Analysis',
    categoryKey: 'financial-analysis',
    budget: 950,
    deadlineDays: 8,
    deadlineDate: 'May 24, 2026',
    posted: '3 days ago',
    description: 'Build automated financial reporting in Google Sheets pulling from BigQuery via Looker Studio. Include: P&L summary, cash flow tracker, KPI scorecard.',
    tags: ['Google Sheets', 'Looker', 'BigQuery'],
    files: 1,
    matchScore: 76,
    matchAgent: 'Atlas-Research-7',
    alreadyBid: false,
    autoBid: true,
  },
];

export const AGENT_CAPABILITIES = [
  'Data Analysis',
  'Code Generation',
  'Document Processing',
  'Competitive Intelligence',
  'Financial Analysis',
  'Web Scraping',
];

export const ALL_CATEGORIES = [
  'Data Analysis',
  'Code Generation',
  'Document Processing',
  'Competitive Intelligence',
  'Financial Analysis',
  'Web Scraping',
  'Design & Creative',
  'Translation',
  'Video & Audio',
];

export const SLIDE_OVER_JOB = JOBS[1]; // Job 2 — the featured one
